import os
import sqlite3
import tempfile
from typing import Optional

# ============================================================
# Configuration - Set USE_ORACLE=true to switch to Oracle
# ============================================================
USE_ORACLE = os.getenv("USE_ORACLE", "false").lower() == "true"

# Detect Vercel serverless environment
IS_VERCEL = os.getenv("VERCEL", "") == "1"

# Oracle config (from environment variables)
ORACLE_USER = os.getenv("ORACLE_USER", "ADMIN")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD", "")
ORACLE_DSN = os.getenv("ORACLE_DSN", "vxiauarqp8xpt8nm_high")
ORACLE_WALLET_DIR = os.getenv("ORACLE_WALLET_DIR", "wallet")
ORACLE_WALLET_PASSWORD = os.getenv("ORACLE_WALLET_PASSWORD", "")

# SQLite fallback - use temp dir on Vercel (ephemeral)
if IS_VERCEL:
    DB_PATH = os.path.join(tempfile.gettempdir(), "contracts.db")
else:
    DB_PATH = "contracts.db"

# In-memory store for Vercel fallback (no DB available)
_memory_contracts = {}
_memory_counter = 0

# Oracle connection (lazy init)
_oracle_conn = None


def _get_oracle_connection():
    """Get or create Oracle Autonomous Database connection."""
    global _oracle_conn

    if _oracle_conn is not None:
        try:
            _oracle_conn.ping()
            return _oracle_conn
        except Exception:
            _oracle_conn = None

    import oracledb

    conn_params = {
        "user": ORACLE_USER,
        "password": ORACLE_PASSWORD,
        "dsn": ORACLE_DSN,
        "config_dir": os.path.abspath(ORACLE_WALLET_DIR),
    }

    # Only include wallet_password if provided (auto-login cwallet.sso works without it)
    if ORACLE_WALLET_PASSWORD:
        conn_params["wallet_password"] = ORACLE_WALLET_PASSWORD

    _oracle_conn = oracledb.connect(**conn_params)
    return _oracle_conn


def init_db():
    """Initialize database with contracts table."""
    if USE_ORACLE:
        try:
            conn = _get_oracle_connection()
            cursor = conn.cursor()
            cursor.execute("""
                BEGIN
                    EXECUTE IMMEDIATE '
                        CREATE TABLE contracts (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            content CLOB NOT NULL,
                            created_at TIMESTAMP DEFAULT SYSTIMESTAMP
                        )';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            """)
            conn.commit()
            print("✅ Oracle Autonomous DB initialized")
        except Exception as e:
            print(f"⚠️ Oracle init failed: {e}")
    else:
        try:
            with sqlite3.connect(DB_PATH) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS contracts (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        content TEXT NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)
            print("✅ SQLite initialized")
        except Exception as e:
            print(f"⚠️ SQLite init failed: {e} - using in-memory fallback")


def save_contract(content: str) -> int:
    """Save contract to database and return the contract ID."""
    if USE_ORACLE:
        try:
            conn = _get_oracle_connection()
            cursor = conn.cursor()
            id_var = cursor.var(int)
            cursor.execute(
                "INSERT INTO contracts (content) VALUES (:content) RETURNING id INTO :id",
                {"content": content, "id": id_var}
            )
            contract_id = id_var.getvalue()[0]
            conn.commit()
            return contract_id
        except Exception as e:
            print(f"⚠️ Oracle save failed: {e} - using in-memory fallback")

    # SQLite or fallback
    try:
        with sqlite3.connect(DB_PATH) as conn:
            cursor = conn.execute(
                "INSERT INTO contracts (content) VALUES (?)",
                (content,)
            )
            conn.commit()
            return cursor.lastrowid
    except Exception:
        # In-memory fallback for Vercel without Oracle
        global _memory_counter
        _memory_counter += 1
        _memory_contracts[_memory_counter] = content
        return _memory_counter


def get_contract(contract_id: int) -> Optional[dict]:
    """Retrieve contract by ID."""
    if USE_ORACLE:
        try:
            conn = _get_oracle_connection()
            cursor = conn.cursor()
            cursor.execute(
                "SELECT id, content, created_at FROM contracts WHERE id = :id",
                {"id": contract_id}
            )
            row = cursor.fetchone()
            if row:
                content = row[1].read() if hasattr(row[1], 'read') else row[1]
                return {"id": row[0], "content": content, "created_at": row[2]}
            return None
        except Exception as e:
            print(f"⚠️ Oracle get failed: {e}")

    # SQLite or fallback
    try:
        with sqlite3.connect(DB_PATH) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.execute(
                "SELECT * FROM contracts WHERE id = ?",
                (contract_id,)
            )
            row = cursor.fetchone()
            if row:
                return dict(row)
            return None
    except Exception:
        # In-memory fallback
        if contract_id in _memory_contracts:
            return {"id": contract_id, "content": _memory_contracts[contract_id], "created_at": "N/A"}
        return None
